{"categories": {
  "RENT": ["RENT", "PROPERTY MANAGEMENT"],
  "SALARY": ["PAYROLL", "SALARY", "WAGES"],
  "GROCERIES": ["WOOLWORTHS", "COLES"],
  "UTILITIES": ["ENERGY", "WATER", "TELSTRA"],
  "FEES": ["FEE", "OVERDRAWN"],
  "BNPL": ["AFTERPAY", "ZIP"],
  "CHILD_SUPPORT": ["CHILD SUPPORT"],
  "TRANSFER": ["TRANSFER"]
}}
